# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mustafalo < Formula
  desc ""
  homepage "https://github.com/MustafaLo/noted"
  version "1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MustafaLo/noted/releases/download/v1.1/noted-cli_1.1_darwin_amd64.tar.gz"
      sha256 "fccd7391139b2f83bd79d24481109874b9cdede6b9ab3dc6522f4e52c903f6bc"

      def install
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MustafaLo/noted/releases/download/v1.1/noted-cli_1.1_darwin_arm64.tar.gz"
      sha256 "7e7f056bd04924a9f8c07ef88eac3f1f91e00899951e34ac8cb6adcc29249caa"

      def install
        bin.install "noted"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MustafaLo/noted/releases/download/v1.1/noted-cli_1.1_linux_amd64.tar.gz"
        sha256 "355a7c141e00aa28691410ca26445bec1c01683e5a0f0ea51d3d81c9c297c800"

        def install
          bin.install "noted"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MustafaLo/noted/releases/download/v1.1/noted-cli_1.1_linux_arm64.tar.gz"
        sha256 "d8faec9033a3ec596fa7910dae9f4449f269a9428f07fbb961eb0b001c45ddfe"

        def install
          bin.install "noted"
        end
      end
    end
  end
end
