# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noted < Formula
  desc ""
  homepage "https://github.com/MustafaLo/noted"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MustafaLo/noted/releases/download/v1.0.1/noted_1.0.1_darwin_amd64.tar.gz"
      sha256 "21d90eed114bb0ba7001be1d7d3834193c213cf2933345464b77f543b89341a9"

      def install
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MustafaLo/noted/releases/download/v1.0.1/noted_1.0.1_darwin_arm64.tar.gz"
      sha256 "e0fd72ddaa8d509a824ed6915b6d25d60a923d2170d09837818cfd2a2e41abe5"

      def install
        bin.install "noted"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MustafaLo/noted/releases/download/v1.0.1/noted_1.0.1_linux_amd64.tar.gz"
        sha256 "1d13086fa6a2ab5ad1df4b845e5c77611b64afbd527df8b430238be008816425"

        def install
          bin.install "noted"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MustafaLo/noted/releases/download/v1.0.1/noted_1.0.1_linux_arm64.tar.gz"
        sha256 "18f84df9e0bb0d5857ed41a8bea33216567c10005ab848ec9db229d75f8909f4"

        def install
          bin.install "noted"
        end
      end
    end
  end
end
