# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noted < Formula
  desc ""
  homepage "https://github.com/MustafaLo/noted"
  version "1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MustafaLo/noted/releases/download/v1.1/noted-cli_1.1_darwin_amd64.tar.gz"
      sha256 "10b6c8fab5dcf1772f1eeacff05c8216a66d3812f03143fa88ee849c48b5b076"

      def install
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MustafaLo/noted/releases/download/v1.1/noted-cli_1.1_darwin_arm64.tar.gz"
      sha256 "726012c66d6607b8382438142f12ef5e563cb03717f2a54f38061d8f1b6784c8"

      def install
        bin.install "noted"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MustafaLo/noted/releases/download/v1.1/noted-cli_1.1_linux_amd64.tar.gz"
        sha256 "42caa0a32e14d3f97a5de93e22f7cb2e490045857a936a321914565a111b5337"

        def install
          bin.install "noted"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MustafaLo/noted/releases/download/v1.1/noted-cli_1.1_linux_arm64.tar.gz"
        sha256 "0643af7a83127434b3bb4f2d1bd59a970efab27266aea68794dca1d1726641b7"

        def install
          bin.install "noted"
        end
      end
    end
  end
end
