# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noted < Formula
  desc ""
  homepage "https://github.com/MustafaLo/noted"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MustafaLo/noted/releases/download/v1.0.0/noted_1.0.0_darwin_amd64.tar.gz"
      sha256 "dcbbe531c71248733d57a37a88434e0b44c211fe8065077dd27fc54057150946"

      def install
        bin.install "noted"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MustafaLo/noted/releases/download/v1.0.0/noted_1.0.0_darwin_arm64.tar.gz"
      sha256 "1ae3f171cc16c130f983ef1137e2f5de904bfb36fee9abee9cec04ab4bb92084"

      def install
        bin.install "noted"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MustafaLo/noted/releases/download/v1.0.0/noted_1.0.0_linux_amd64.tar.gz"
        sha256 "35d2f070d1ecb5715ee104a5da13cacdb81345cc311d72c085395386a28e347b"

        def install
          bin.install "noted"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MustafaLo/noted/releases/download/v1.0.0/noted_1.0.0_linux_arm64.tar.gz"
        sha256 "66a181b2e8ff52a7908a1139a74398d562c4d71d4281f9e8c4d6a464c5e4b845"

        def install
          bin.install "noted"
        end
      end
    end
  end
end
